### ISSUE TITLE
error in running glvq_iris.py 

### ISSUE THREAD

**Issue by FeryelZoghlamii** [si-cim/protoflow#6]
1. When cloning the repository I have not 'logs' folder so I had to create it manually.
2. When running the example I got this error: 

Traceback (most recent call last):
  File "c:/Users/ZoghlamF/Downloads/personal/Mittweida/protoflow/protoflow/examples/glvq_iris.py", line 56, in <module>
    batch_size=BATCH_SIZE)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\protoflow\applications\glvq.py", line 260, in fit
    **kwargs)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 397, in fit
    prefix='val_')
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 757, in on_start
    self.callbacks._call_end_hook(mode)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 262, in _call_end_hook
    self.on_train_end()
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 379, in on_train_end
    callback.on_train_end(logs)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\protoflow\experimental\callbacks\callbacks.py", line 168, in on_train_end
    animation.save(vid, fps=self.fps, dpi=self.dpi)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\matplotlib\animation.py", line 1102, in save
    alt_writer = next(writers, None)
TypeError: 'MovieWriterRegistry' object is not an iterator

Any help?

**Comment by theblackfly** [comment]
The error is probably because matplotlib cannot find the tools it needs to convert the animation into a video file. Try installing [ffmpeg](https://ffmpeg.org/download.html) first. Alternatively, you can remove the visualization callback. It is not essential for training the model.

**Comment by FeryelZoghlamii** [comment]
I already have ffmpeg 1.4 installed but still get the same error. When I remove the visualization callback I got another error for the earlystopping callback:
Traceback (most recent call last):
  File "c:/Users/ZoghlamF/Downloads/personal/Mittweida/protoflow/protoflow/examples/glvq_iris.py", line 57, in <module>
    batch_size=BATCH_SIZE)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\protoflow\applications\glvq.py", line 229, in fit
    callbacks.append(tf.keras.callbacks.TerminateOnNaN())
AttributeError: 'EarlyStopping' object has no attribute 'append'
???

**Comment by theblackfly** [comment]
Make sure you pass `callbacks` as a python list. Even if there is only one callback.

**Comment by FeryelZoghlamii** [comment]
Now I have the same error as in the other opened issue:
"tensorflow.python.eager.profiler.ProfilerNotRunningError: Cannot stop profiling. No profiler is running."

**Comment by FeryelZoghlamii** [comment]
Error solved! upgrade the tensorflow version to the version 2.2.0-rc2 with the command:
pip install tensorflow==2.2.0-rc2
Thank you!
