### ISSUE TITLE
Error in running lvqmln.py

### ISSUE THREAD

**Issue by FeryelZoghlamii** [si-cim/protoflow#7]
When running the script I got this error:
Traceback (most recent call last):
  File "c:/Users/ZoghlamF/Downloads/personal/Mittweida/protoflow/protoflow/examples/lvqmln_mnist.py",
line 64, in <module>
    batch_size=BATCH_SIZE)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\protoflow\applications\glvq.py", line 260, in fit
    **kwargs)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 397, in fit
    prefix='val_')
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 757, in on_start
    self.callbacks._call_end_hook(mode)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 262, in _call_end_hook
    self.on_train_end()
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 379, in on_train_end
    callback.on_train_end(logs)
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 1720, in on_train_end
    self._log_trace()
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 1747, in _log_trace
    profiler_outdir=os.path.join(self._log_write_dir, 'train'))
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\ops\summary_ops_v2.py", line 1240, in trace_export
    _profiler.save(profiler_outdir, _profiler.stop())
  File "C:\Users\ZoghlamF.INFINEON\Documents\My Documents\Anaconda\lib\site-packages\tensorflow_core\python\eager\profiler.py", line 99, in stop
    'Cannot stop profiling. No profiler is running.')
tensorflow.python.eager.profiler.ProfilerNotRunningError: Cannot stop profiling. No profiler is running.

**Comment by theblackfly** [comment]
https://github.com/tensorflow/tensorboard/issues/2819 might help.

**Comment by FeryelZoghlamii** [comment]
I tried already all the suggestions and more but still get the same error :(

**Comment by FeryelZoghlamii** [comment]
Error solved! upgrade the tensorflow version to the version 2.2.0-rc2 with the command:
pip install tensorflow==2.2.0-rc2
Thank you!
